openapi: 3.1.0
info:
  title: CogniForge API Gateway
  description: '# بوابة API المركزية


    نقطة الدخول الموحدة لجميع الخدمات المصغرة في نظام CogniForge.


    ## الميزات

    - **توجيه ذكي**: توجيه الطلبات إلى الخدمات المناسبة

    - **موازنة الحمل**: توزيع الطلبات بين نسخ الخدمات

    - **إعادة المحاولة**: إعادة المحاولة التلقائية عند الفشل

    - **فحص الصحة**: مراقبة صحة جميع الخدمات

    - **تحديد المعدل**: حماية من الطلبات الزائدة


    ## المصادقة

    جميع الطلبات تتطلب JWT token:

    ```

    Authorization: Bearer <token>

    ```

    '
  version: 1.0.0
  contact:
    name: CogniForge Support
    email: support@cogniforge.ai
servers:
- url: http://localhost:8000/v1/gateway
  description: Local Development
- url: https://api.cogniforge.ai/v1/gateway
  description: Production
tags:
- name: Gateway
  description: عمليات البوابة الأساسية
- name: Services
  description: إدارة الخدمات المسجلة
paths:
  /health:
    get:
      summary: فحص صحة البوابة
      description: يفحص صحة البوابة وجميع الخدمات المسجلة
      operationId: getGatewayHealth
      tags:
      - Gateway
      responses:
        '200':
          description: البوابة والخدمات صحية
          content:
            application/json:
              schema:
                type: object
                properties:
                  gateway:
                    type: string
                    example: healthy
                  services:
                    type: object
                    additionalProperties:
                      $ref: '#/components/schemas/ServiceHealth'
                  summary:
                    type: object
                    properties:
                      healthy:
                        type: integer
                        description: عدد الخدمات الصحية
                      total:
                        type: integer
                        description: إجمالي الخدمات
                      percentage:
                        type: number
                        format: float
                        description: نسبة الخدمات الصحية
              example:
                message: مثال لاستجابة
  /services:
    get:
      summary: عرض الخدمات المسجلة
      description: يعرض قائمة بجميع الخدمات المسجلة في البوابة
      operationId: listServices
      tags:
      - Services
      responses:
        '200':
          description: قائمة الخدمات
          content:
            application/json:
              schema:
                type: object
                properties:
                  services:
                    type: array
                    items:
                      $ref: '#/components/schemas/ServiceInfo'
                  count:
                    type: integer
                    description: عدد الخدمات
              example:
                message: مثال لاستجابة
  /services/{service-name}/paths/{sub-path}:
    get:
      summary: توجيه طلب GET
      description: يوجه طلب GET إلى الخدمة المحددة
      operationId: proxyGetRequest
      tags:
      - Gateway
      parameters:
      - name: service-name
        in: path
        required: true
        schema:
          type: string
        description: اسم الخدمة المستهدفة
      - name: sub-path
        in: path
        required: true
        schema:
          type: string
        description: المسار في الخدمة المستهدفة
      responses:
        '200':
          description: استجابة من الخدمة
        '404':
          description: الخدمة غير موجودة
          content:
            application/json: &id001
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: مثال لاستجابة
            application/problem+json: *id001
        '502':
          description: فشل الاتصال بالخدمة
          content:
            application/json: &id002
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: مثال لاستجابة
            application/problem+json: *id002
        '503':
          description: الخدمة غير متاحة
          content:
            application/json: &id003
              schema:
                $ref: '#/components/schemas/Error'
              example:
                message: مثال لاستجابة
            application/problem+json: *id003
    post:
      summary: توجيه طلب POST
      description: يوجه طلب POST إلى الخدمة المحددة
      operationId: proxyPostRequest
      tags:
      - Gateway
      parameters:
      - name: service-name
        in: path
        required: true
        schema:
          type: string
        description: المعامل service-name المطلوب لتنفيذ العملية
      - name: sub-path
        in: path
        required: true
        schema:
          type: string
        description: المعامل sub-path المطلوب لتنفيذ العملية
      requestBody:
        content:
          application/json:
            schema:
              type: object
            example:
              message: مثال لطلب
      responses:
        '200':
          description: استجابة من الخدمة
        '404':
          description: الخدمة غير موجودة
        '502':
          description: فشل الاتصال بالخدمة
        '503':
          description: الخدمة غير متاحة
      security:
      - BearerAuth: []
components:
  schemas:
    ServiceHealth:
      type: object
      properties:
        healthy:
          type: boolean
          description: هل الخدمة صحية
        response_time_ms:
          type: number
          format: float
          nullable: true
          description: وقت الاستجابة بالميلي ثانية
        last_check:
          type: string
          format: date-time
          description: آخر فحص
        error:
          type: string
          nullable: true
          description: رسالة الخطأ إن وجدت
      example:
        healthy: true
        response_time_ms: 0
        last_check: "2024-01-01T12:00:00Z"
        error: string
    ServiceInfo:
      type: object
      properties:
        name:
          type: string
          description: اسم الخدمة
        base_url:
          type: string
          format: uri
          description: عنوان URL الأساسي
        health_path:
          type: string
          description: مسار فحص الصحة
        timeout:
          type: integer
          description: مهلة الطلب بالثواني
      example:
        name: string
        base_url: "https://example.com"
        health_path: string
        timeout: 0
    Error:
      type: object
      properties:
        detail:
          type: string
          description: تفاصيل الخطأ
      example:
        detail: string
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
- BearerAuth: []
