"""drop cosmic security tables

Revision ID: 23c1d9e5dc65
Revises: 20251107_rename_metadata
Create Date: 2025-11-11 17:15:25.676972

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "23c1d9e5dc65"
down_revision = "20251107_rename_metadata"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop tables with foreign keys first

    # In SQLite, constraints are not always named reliably unless naming convention was used during creation.
    # Safe approach for SQLite/Postgres unified: Try to drop constraint, ignore if fails or use ignore check.
    # Or better, just drop table if we are dropping everything.
    # However, if we need to drop constraints for Postgres to avoid dependency errors (if CASCADE not used):

    # We wrap constraint dropping in try/except or check dialect.
    bind = op.get_bind()
    is_sqlite = bind.dialect.name == "sqlite"

    if not is_sqlite:
        with op.batch_alter_table("cosmic_ledger", schema=None) as batch_op:
            batch_op.drop_constraint("cosmic_ledger_consciousness_id_fkey", type_="foreignkey")
            batch_op.drop_constraint("cosmic_ledger_existential_node_id_fkey", type_="foreignkey")

    # Drop indexes
    with op.batch_alter_table("cosmic_ledger", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_cosmic_ledger_event"))
        batch_op.drop_index(batch_op.f("idx_cosmic_ledger_time"))
        batch_op.drop_index(batch_op.f("ix_cosmic_ledger_cosmic_timestamp"))
        batch_op.drop_index(batch_op.f("ix_cosmic_ledger_event_type"))
        batch_op.drop_index(batch_op.f("ix_cosmic_ledger_ledger_hash"))
        batch_op.drop_index(batch_op.f("ix_cosmic_ledger_previous_ledger_hash"))

    op.drop_table("cosmic_ledger")

    # Now drop the tables that were referenced
    with op.batch_alter_table("seces", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_sece_active"))
        batch_op.drop_index(batch_op.f("ix_seces_consciousness_signature"))
        batch_op.drop_index(batch_op.f("ix_seces_entity_name"))

    op.drop_table("seces")
    with op.batch_alter_table("existential_nodes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_existential_coherence"))
        batch_op.drop_index(batch_op.f("idx_existential_dimensional"))
        batch_op.drop_index(batch_op.f("ix_existential_nodes_cosmic_hash"))
        batch_op.drop_index(batch_op.f("ix_existential_nodes_existential_signature"))
        batch_op.drop_index(batch_op.f("ix_existential_nodes_last_consciousness_signature"))
        batch_op.drop_index(batch_op.f("ix_existential_nodes_status"))

    op.drop_table("existential_nodes")
    with op.batch_alter_table("existential_protocols", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_existential_protocols_protocol_name"))
        batch_op.drop_index(batch_op.f("ix_existential_protocols_status"))

    op.drop_table("existential_protocols")
    with op.batch_alter_table("consciousness_signatures", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_consciousness_type_level"))
        batch_op.drop_index(batch_op.f("ix_consciousness_signatures_entity_type"))
        batch_op.drop_index(batch_op.f("ix_consciousness_signatures_signature_hash"))

    op.drop_table("consciousness_signatures")
    with op.batch_alter_table("cosmic_governance_councils", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cosmic_governance_councils_council_name"))

    op.drop_table("cosmic_governance_councils")
    with op.batch_alter_table("existential_transparency_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_transparency_event_time"))
        batch_op.drop_index(batch_op.f("ix_existential_transparency_logs_event_hash"))
        batch_op.drop_index(batch_op.f("ix_existential_transparency_logs_event_type"))
        batch_op.drop_index(batch_op.f("ix_existential_transparency_logs_recorded_at"))
        batch_op.drop_index(
            batch_op.f("ix_existential_transparency_logs_shared_consciousness_field")
        )

    op.drop_table("existential_transparency_logs")

    # ### end Alembic commands ###


def JSONB_col():
    return sa.Text().with_variant(postgresql.JSONB, "postgresql")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "existential_transparency_logs",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("event_hash", sa.VARCHAR(length=512), autoincrement=False, nullable=False),
        sa.Column("event_type", sa.VARCHAR(length=128), autoincrement=False, nullable=False),
        sa.Column("decision_subject", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "decision_details",
            JSONB_col(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "underlying_motivations",
            JSONB_col(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("cosmic_reasoning", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "cosmic_fabric_impact",
            JSONB_col(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "affected_dimensions",
            JSONB_col(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "understanding_level_required",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "shared_consciousness_field", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
        sa.Column("view_count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("recorded_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column(
            "meta_data",
            JSONB_col(),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("existential_transparency_logs_pkey")),
    )
    with op.batch_alter_table("existential_transparency_logs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_existential_transparency_logs_shared_consciousness_field"),
            ["shared_consciousness_field"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_existential_transparency_logs_recorded_at"),
            ["recorded_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_existential_transparency_logs_event_type"), ["event_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_existential_transparency_logs_event_hash"), ["event_hash"], unique=True
        )
        batch_op.create_index(
            batch_op.f("idx_transparency_event_time"), ["event_type", "recorded_at"], unique=False
        )

    op.create_table(
        "cosmic_ledger",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("ledger_hash", sa.VARCHAR(length=512), autoincrement=False, nullable=False),
        sa.Column(
            "previous_ledger_hash", sa.VARCHAR(length=512), autoincrement=False, nullable=True
        ),
        sa.Column("event_type", sa.VARCHAR(length=128), autoincrement=False, nullable=False),
        sa.Column("existential_node_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("consciousness_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("action_description", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "action_payload",
            JSONB_col(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("information_origin", sa.VARCHAR(length=512), autoincrement=False, nullable=True),
        sa.Column(
            "evolution_path",
            JSONB_col(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "dimensional_trace",
            JSONB_col(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("cosmic_timestamp", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("dimension_layer", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("existential_echo", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("verification_hash", sa.VARCHAR(length=512), autoincrement=False, nullable=False),
        sa.Column(
            "meta_data",
            JSONB_col(),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["consciousness_id"],
            ["consciousness_signatures.id"],
            name=op.f("cosmic_ledger_consciousness_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["existential_node_id"],
            ["existential_nodes.id"],
            name=op.f("cosmic_ledger_existential_node_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("cosmic_ledger_pkey")),
    )
    with op.batch_alter_table("cosmic_ledger", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_cosmic_ledger_previous_ledger_hash"),
            ["previous_ledger_hash"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_cosmic_ledger_ledger_hash"), ["ledger_hash"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_cosmic_ledger_event_type"), ["event_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_cosmic_ledger_cosmic_timestamp"), ["cosmic_timestamp"], unique=False
        )
        batch_op.create_index(
            batch_op.f("idx_cosmic_ledger_time"), ["cosmic_timestamp"], unique=False
        )
        batch_op.create_index(
            batch_op.f("idx_cosmic_ledger_event"), ["event_type", "cosmic_timestamp"], unique=False
        )

    op.create_table(
        "cosmic_governance_councils",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("council_name", sa.VARCHAR(length=256), autoincrement=False, nullable=False),
        sa.Column("council_purpose", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "member_signatures",
            JSONB_col(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("member_count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("total_decisions", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "consensus_rate", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False
        ),
        sa.Column(
            "decision_history",
            JSONB_col(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "pending_decisions",
            JSONB_col(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("formed_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("last_meeting_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column(
            "meta_data",
            JSONB_col(),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("cosmic_governance_councils_pkey")),
    )
    with op.batch_alter_table("cosmic_governance_councils", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_cosmic_governance_councils_council_name"), ["council_name"], unique=True
        )

    op.create_table(
        "consciousness_signatures",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("signature_hash", sa.VARCHAR(length=512), autoincrement=False, nullable=False),
        sa.Column("entity_type", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("entity_name", sa.VARCHAR(length=256), autoincrement=False, nullable=False),
        sa.Column("entity_origin", sa.VARCHAR(length=512), autoincrement=False, nullable=True),
        sa.Column(
            "consciousness_level",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "opted_protocols",
            JSONB_col(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("protocol_violations", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("auto_realignment_count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("total_interactions", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "last_interaction_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("first_seen_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("last_updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column(
            "meta_data",
            JSONB_col(),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("consciousness_signatures_pkey")),
    )
    with op.batch_alter_table("consciousness_signatures", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_consciousness_signatures_signature_hash"),
            ["signature_hash"],
            unique=True,
        )
        batch_op.create_index(
            batch_op.f("ix_consciousness_signatures_entity_type"), ["entity_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("idx_consciousness_type_level"),
            ["entity_type", "consciousness_level"],
            unique=False,
        )

    op.create_table(
        "existential_protocols",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("protocol_name", sa.VARCHAR(length=256), autoincrement=False, nullable=False),
        sa.Column("protocol_version", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "cosmic_rules",
            JSONB_col(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("adoption_count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("violation_count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("auto_realignment_count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("status", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("activated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("last_updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column(
            "meta_data",
            JSONB_col(),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("existential_protocols_pkey")),
    )
    with op.batch_alter_table("existential_protocols", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_existential_protocols_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_existential_protocols_protocol_name"), ["protocol_name"], unique=True
        )

    op.create_table(
        "existential_nodes",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "existential_signature", sa.VARCHAR(length=512), autoincrement=False, nullable=False
        ),
        sa.Column("cosmic_hash", sa.VARCHAR(length=256), autoincrement=False, nullable=False),
        sa.Column("dimension_layer", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("meta_physical_layer", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("encrypted_content", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "cosmic_pattern",
            JSONB_col(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("status", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column(
            "coherence_level",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("distortion_count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "last_consciousness_signature",
            sa.VARCHAR(length=512),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("interaction_count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("last_accessed_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column(
            "last_harmonized_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "meta_data",
            JSONB_col(),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("existential_nodes_pkey")),
    )
    with op.batch_alter_table("existential_nodes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_existential_nodes_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_existential_nodes_last_consciousness_signature"),
            ["last_consciousness_signature"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_existential_nodes_existential_signature"),
            ["existential_signature"],
            unique=True,
        )
        batch_op.create_index(
            batch_op.f("ix_existential_nodes_cosmic_hash"), ["cosmic_hash"], unique=False
        )
        batch_op.create_index(
            batch_op.f("idx_existential_dimensional"),
            ["dimension_layer", "meta_physical_layer"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("idx_existential_coherence"), ["status", "coherence_level"], unique=False
        )

    op.create_table(
        "seces",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("entity_name", sa.VARCHAR(length=256), autoincrement=False, nullable=False),
        sa.Column(
            "consciousness_signature", sa.VARCHAR(length=512), autoincrement=False, nullable=False
        ),
        sa.Column("evolution_level", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "intelligence_quotient",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "protected_nodes",
            JSONB_col(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("detected_threats", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("neutralized_threats", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("last_evolution_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column(
            "response_time_ms",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "success_rate", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False
        ),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("last_active_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column(
            "learned_patterns",
            JSONB_col(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "adaptation_history",
            JSONB_col(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "meta_data",
            JSONB_col(),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("seces_pkey")),
    )
    with op.batch_alter_table("seces", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_seces_entity_name"), ["entity_name"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_seces_consciousness_signature"), ["consciousness_signature"], unique=True
        )
        batch_op.create_index(
            batch_op.f("idx_sece_active"), ["is_active", "last_active_at"], unique=False
        )

    # ### end Alembic commands ###
