"""add_admin_ai_chat_system

Revision ID: c670e137ea84
Revises: 20250902_evt_type_idx
Create Date: 2025-09-30 14:34:02.643436

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c670e137ea84"
down_revision = "20250902_evt_type_idx"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_conversations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("conversation_type", sa.String(length=50), nullable=False),
        sa.Column("deep_index_summary", sa.Text(), nullable=True),
        sa.Column("context_snapshot", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("admin_conversations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_admin_conversations_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "admin_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("tokens_used", sa.Integer(), nullable=True),
        sa.Column("model_used", sa.String(length=100), nullable=True),
        sa.Column("latency_ms", sa.Float(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["admin_conversations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("admin_messages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_admin_messages_conversation_id"), ["conversation_id"], unique=False
        )

    with op.batch_alter_table("mission_events", schema=None) as batch_op:
        batch_op.alter_column(
            "event_type",
            existing_type=sa.TEXT(),
            type_=sa.Enum(
                "CREATED",
                "STATUS_CHANGE",
                "PLAN_SELECTED",
                "EXECUTION_STARTED",
                "TASK_STARTED",
                "TASK_COMPLETED",
                "TASK_FAILED",
                "REPLAN_TRIGGERED",
                "REPLAN_APPLIED",
                "MISSION_UPDATED",
                "RISK_SUMMARY",
                "ARCHITECTURE_CLASSIFIED",
                "MISSION_COMPLETED",
                "MISSION_FAILED",
                "FINALIZED",
                name="missioneventtype",
                native_enum=False,
            ),
            existing_nullable=False,
        )
        batch_op.drop_index(batch_op.f("ix_mission_events_mission_created_type"))
        batch_op.create_index(
            batch_op.f("ix_mission_events_event_type"), ["event_type"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("mission_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mission_events_event_type"))
        batch_op.create_index(
            batch_op.f("ix_mission_events_mission_created_type"),
            ["mission_id", "created_at", "event_type"],
            unique=False,
        )
        batch_op.alter_column(
            "event_type",
            existing_type=sa.Enum(
                "CREATED",
                "STATUS_CHANGE",
                "PLAN_SELECTED",
                "EXECUTION_STARTED",
                "TASK_STARTED",
                "TASK_COMPLETED",
                "TASK_FAILED",
                "REPLAN_TRIGGERED",
                "REPLAN_APPLIED",
                "MISSION_UPDATED",
                "RISK_SUMMARY",
                "ARCHITECTURE_CLASSIFIED",
                "MISSION_COMPLETED",
                "MISSION_FAILED",
                "FINALIZED",
                name="missioneventtype",
                native_enum=False,
            ),
            type_=sa.TEXT(),
            existing_nullable=False,
        )

    with op.batch_alter_table("admin_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_admin_messages_conversation_id"))

    op.drop_table("admin_messages")
    with op.batch_alter_table("admin_conversations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_admin_conversations_user_id"))

    op.drop_table("admin_conversations")
    # ### end Alembic commands ###
